// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCx3GsY6hWk0fsX2fzWsMfvfzeGm1p1jRA',
    appId: '1:33541448236:web:64b30ce796e53fba18e789',
    messagingSenderId: '33541448236',
    projectId: 'table-pos',
    authDomain: 'table-pos.firebaseapp.com',
    storageBucket: 'table-pos.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAfE04TymKUy_y8mpGJSExnY6sHKD0JX6M',
    appId: '1:33541448236:android:5fd6ef5e9c4d500518e789',
    messagingSenderId: '33541448236',
    projectId: 'table-pos',
    storageBucket: 'table-pos.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDhc6vw_Cf6Hh7quc7q45v5HPUh7cFtic4',
    appId: '1:33541448236:ios:7745256a2b744fdb18e789',
    messagingSenderId: '33541448236',
    projectId: 'table-pos',
    storageBucket: 'table-pos.firebasestorage.app',
    iosBundleId: 'com.tableside.tablesidePos',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCx3GsY6hWk0fsX2fzWsMfvfzeGm1p1jRA',
    appId: '1:33541448236:web:2a6fb73c3186658618e789',
    messagingSenderId: '33541448236',
    projectId: 'table-pos',
    authDomain: 'table-pos.firebaseapp.com',
    storageBucket: 'table-pos.firebasestorage.app',
  );
}
