/// Keeps the Firebase-backed workspace opt-in while the local demo remains
/// useful for reviewing the POS without a signed-in Firebase user.
///
/// The platform-specific Firebase configuration is generated by FlutterFire in
/// `lib/firebase_options.dart`; it contains the public app identifiers needed
/// by Firebase and is intentionally committed to source control.
abstract final class FirebaseRuntimeConfig {
  static const enabled = bool.fromEnvironment('TABLESIDE_USE_FIREBASE');
}
